---
title: "TestScript"
author: "Stanley"
date: "13/4/2020"
output: pdf_document
---

# Preamble of libraries
```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tm)
library(SnowballC)
library(wordcloud)
library(RColorBrewer)

```

# Loading the data
```{r,echo=FALSE}

df<- read_csv("data/_raw/COVID19_open_line_list.csv")
df

```

## Extracting only symptoms
```{r pressure, echo=FALSE}
sym<-df %>%
  select(symptoms) %>%
  drop_na() %>%
  str_split(.," , ")

```

# Extracting symptoms alternative
```{r}

s<-as.tibble(df$symptoms)


colnames(s)<-as.character("symptom")


# 
s2<-s %>%
  transform(symptom = str_split(symptom, ",|;")) %>%
  unnest() %>%
  drop_na() %>%
  as.data.frame(str_replace(s2$symptom,"^ ", "")) %>%
  distinct_all()


nys<-as.data.frame(str_replace(s2$symptom,"^ ", ""))

colnames(nys)<-as.character("s")


nys %>%
  distinct(s)


```

# Trasforming the symptom vector
```{r}
sym[[1]]
  
docs<-Corpus(VectorSource(sym[[1]]))


toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))


docs <- tm_map(docs, toSpace, ",")
docs <- tm_map(docs, toSpace, " ")
docs <- tm_map(docs, toSpace, "\\|")
docs <- tm_map(docs, toSpace, "\n")


inspect(docs)

```


# Removing words
```{r}
# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))

# Remove numbers
docs <- tm_map(docs, removeNumbers)

# Remove english common stopwords
docs <- tm_map(docs, removeWords, stopwords("english"))

# Remove your own stop word
# specify your stopwords as a character vector
# docs <- tm_map(docs, removeWords, c("blabla1", "blabla2")) 

# Remove punctuations
docs <- tm_map(docs, removePunctuation)

# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)

# Text stemming
# docs <- tm_map(docs, stemDocument)

inspect(docs)
```


# Making the matrix
```{r}

dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)

head(d, 20)
```

# Creating the wordcloud
```{r}

wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.2, 
          colors=brewer.pal(10, "RdBu"))

```

# Making barplot
```{r}

barplot(d[1:10,]$freq, las = 2, names.arg = d[1:10,]$word,
        col ="lightblue", main ="Symptoms",
        ylab = "Count")

```


